BOARD = zcu104
#UBOOT_CONFIG = zc70x #TODO does it really matter?
UBOOT_CONFIG = zcu104
#BOARD_MODEL = xilinx.com:zc706:part0:1.0
BOARD_MODEL = xilinx.com:zcu102:part0:3.2
#PART = xc7z045ffg900-2
PART = xczu9eg-ffvb1156-2-e

TOP_MODULE_PROJECT = zynq.boom
CONFIG ?= DCacheBoomZynqConfig
#CONFIG ?= SmallBoomZynqConfig

include ../common/Makefrag




